[package]
name = "RookBot"
version = "0.1.0"
edition = "2021"

[dependencies]


num-traits = "0.2.19"

rand = "0.9.0"
fxhash = "0.2.1"
derive_more = { version = "2.0.1", features = ["full"] }

[profile.perf]
inherits = "release"
debug = true
lto = false
codegen-units = 1
